image: archlinux
packages:
  - systemd
  - linux-api-headers
  - libx11
  - libxrandr
  - libxext
  - libxss
  - ddcutil
  - libmodule
sources:
  - https://github.com/FedeDP/Clightd
tasks:
  - build: |
      cd Clightd
      make debug
      make DISABLE_GAMMA=1 debug
      make DISABLE_DPMS=1 debug
      make DISABLE_IDLE=1 debug
      make DISABLE_DDC=1 debug
      make DISABLE_GAMMA=1 DISABLE_DPMS=1 DISABLE_IDLE=1 DISABLE_DDC=1 debug
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
