image: archlinux
packages:
  - systemd
  - linux-api-headers
  - libx11
  - libxrandr
  - libxext
  - libxss
  - ddcutil
  - libmodule
  - cmake
sources:
  - https://github.com/FedeDP/Clightd
tasks:
  - build: |
      cd Clightd
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug ..
      make
      rm -rf *
      cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_GAMMA=1 ..
      make
      rm -rf *
      cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_DPMS=1 ..
      make
      rm -rf *
      cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_IDLE=1 ..
      make
      rm -rf *
      cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_DDC=1 ..
      make
      rm -rf *
      cmake -DCMAKE_BUILD_TYPE=Debug -DDISABLE_GAMMA=1 -DDISABLE_DPMS=1 -DDISABLE_IDLE=1 -DDISABLE_DDC=1 ..
      make
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
