sudo: required

notifications:
  email:
    on_success: change
    on_failure: always

language: c

services:
  - docker

compiler:
  - gcc
  - clang

arch:
    packages:
        - systemd
        - linux-api-headers
        - libx11
        - libxrandr
        - libxext
        - libxss
        - libmodule
        - ddcutil
    script:
        - "echo $CC"
        - make debug
        - make DISABLE_GAMMA=1 debug
        - make DISABLE_DPMS=1 debug
        - make DISABLE_IDLE=1 debug
  	- make DISABLE_DDC=1 debug
        - make DISABLE_GAMMA=1 DISABLE_DPMS=1 DISABLE_IDLE=1 DISABLE_DDC=1 debug

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

